# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
