# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork2', '0002_profile_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content_type',
            field=models.CharField(max_length=50),
        ),
    ]
