# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork2', '0005_auto_20170220_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, default='images/defaultuserpicture.png', upload_to='images'),
        ),
    ]
